### ISSUE TITLE
Make nested struct generation works

### ISSUE THREAD

**Issue by ying-jeanne** [grafana/cuetsy#19]
An example of expected input/output of cuetsy: https://gist.github.com/sdboyer/5d0b9e8e7ba0f60e427c84626a0eb11a

**Comment by sdboyer** [comment]
Indeed, we absolutely need to have codegen work for nested structs. It may be kinda tricky to implement, but there's no way around it.

**Comment by ying-jeanne** [comment]
The generation of nested struct itself is easy, but to generate the default is a bit tricky. writing down some test cases that should be covered by the code.
(pre-calculate the depth of nested struct, then go iteratively would not work? since a nested struct could contains several children, and each of them could have different depth?)
