### ISSUE TITLE
Convert cue import into typescript

### ISSUE THREAD

**Issue by ying-jeanne** [grafana/cuetsy#24]
an example of cue import https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/timeseries/models.cue

**Comment by ying-jeanne** [comment]
an example would be something in cue:
```
import (
    ui "github.com/grafana/grafana/packages/grafana-schema/src/schema"
)
```
to 
```
import * as ui from "@grafana/ui"
```

**Comment by sdboyer** [comment]
What we want here is, i think, an entirely separate generator from our existing `func Generate()`, on the expectation that we're going to want to handle import generation separately from generating the body. This is a necessary outgrowth of our existing type signatures - if we want `Generate()` to continue taking a `cue.Value` (and we do), then swimming back upstream from the `cue.Value` to finding import statements becomes difficult, so we should handle them separately.

This would be a reasonable signature:

```go
type ImportMapper func(*ast.ImportSpec) (string, error) // Already in cuetsy, but needs type sig change
func GenerateImports(imports []*ast.ImportSpec, mapper ImportMapper) ([]byte, error) {}
```

We could, at some later point, add an e.g. `func GenerateFile()`, which itself would internally call `GenerateImports()` and `Generate()`, but for now we can leave it up to the user to put these bits together themselves.
