### ISSUE TITLE
Add a new public cuetsy functions to take context in order to dereference the cue input and generate ts to a certain level

### ISSUE THREAD

**Issue by ying-jeanne** [grafana/cuetsy#29]

**Comment by ying-jeanne** [comment]
It might not be necessary now, since we can get context from cue.Value directly. so we can actually pass the right cue.Value when calling the generate function?

**Comment by sdboyer** [comment]
Yeah, with the new API that allows us to extract a `cuecontext.Context` from a `cue.Value`, we no longer need to worry about using the right context.
