### ISSUE TITLE
Generate referenced enum defaults correctly

### ISSUE THREAD

**Issue by sdboyer** [grafana/cuetsy#35]
Currently, when there's an enum with a default value that's referenced, we generate the reference to it like this:

<table style="width:100%">
<tr>
<th>CUE</th>
<th>TS</th>
</tr>
<tr>
<td>

```cue
package cuetsy

AutoCamel: *"foo" | "bar" @cuetsy(kind="enum")
Ref: {
  ac: AutoCamel
} @cuetsy(kind="interface")
```

</td>
<td>

```ts
export enum AutoCamel {
  Foo = "foo",
  Bar = "bar",
}

export const defaultAutoCamel: AutoCamel = AutoCamel.Foo

export interface Ref {
  ac: AutoCamel
}

export const defaultRef: Ref = {
  ac: "foo"
}
```
</td>
</tr>
</table>

This fails typechecking. The default should be:

```ts
export const defaultRef: Ref = {
  ac: AutoCamel.Foo
}
```

[This (disabled) test](https://github.com/grafana/cuetsy/blob/main/testdata/imports/compose_enums.txtar) contains a more exhaustive set of cases to check, but they all ultimately amount to the same problem.

**Comment by sh0rez** [comment]
sorta blocked on https://github.com/cue-lang/cue/discussions/1389

**Comment by sdboyer** [comment]
Note - OP is not actually quite true. We do fine with the basic case. Things get screwy when we try to do things across references.

There also seems to be issues related to wonkiness with attributes transferring across unification.
