### ISSUE TITLE
Translate empty struct types as `Record<string, unknown>` instead of `{}`

### ISSUE THREAD

**Issue by sdboyer** [grafana/cuetsy#59]
Currently, cuetsy translates an empty struct:

```cue
f: {...} @cuetsy(@kind="type")
```

To an empty object:

```ts
export type f = {};
```

It appears that `{}` is subtly different than the primitive type `object` in TypeScript's type system, as indicated by [this playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgEJwM4oN4ChnJQQygQCMAXMgErGhwBGANhANz6F0gQBMVA9gwBWEBGHYEiJbgGYq2AL6tkAehXIAgkwz9kwGMgDyw0WFwLcuUJFiIUtaYxbI8BHQFs6EJgBMqGMChQAHNzS2toeCRkAHV+KABrDAAeABUyABpkVJ4s1JkAPmQIAA9IEB8MNEwcDjVYgAsIEGKy5p8Q5DhkEm8fZAB3YDAGruQQfhAAWgh3AAcwAE9kQRExZCW5iAy69RGUTZQEJoQE6E4ARwBXYCIqq6qwXTg5uaZluBaIqCwxYEmAHQcKSkSjZMjIABkNC4TjYu040nIVHSynqh2KUCg8UsBHqqQawCqRK62l0zRg8SQ-X0GyarXKPgg-V6vmQDUwdJQcyC7mGwAAbhAEatTBtFltgVxeCieFCXEoESDuHxsjw0XsJShoNioLjVOoABL8AYQIVQLIDJotUqMzqfYrzJYrExiLLDADkVQmYHGoggGAwcCgiwRTy6r3eXS+4GgvzA-xahwB2XpGP4BmVEBkegwIA9vtFYimock0rk2Rk7AsVljtmiABF+AGQHA4ok0pk1XlCgz2lV0FgXFKkWDUQbxVtMbqR6RVTkNZPtVicWWkRX8tXLPUNBU9BUIMzLYTnKaukQelTmRtdAhJpSoO4b1yl1VgoLmrh6qBqkOH4jQWjfos1yQYjgdOYrl9H9ug6GAYGgZpfR5YA+QTIUv01Kd-yzGRcDvEAAkvfgqHbJJkgcehmG2GFHGorIAiCEBgiKABeYc11BeQODcfhPFZPxkAAIkpfghJ2AgFAkgCVW4gheP44A+ioISGGDcSOCk2dZBUq1+H4OYMCUnx9J8FgNIUIA)). I _think_ `object` is what we want here, but will probably have to research a bit further before committing to the approach.

**Comment by ArturWierzbicki** [comment]
It should probably be `Record<string, unknown>` if we want to express the equivalent of "any struct", see https://www.reddit.com/r/typescript/comments/tq3m4f/the_difference_between_object_and_recordstring/

**Comment by sdboyer** [comment]
Interesting! Yes, `object` clearly does still allow array types, which is a possibility we want to eliminate.
