### ISSUE TITLE
why not use HOF?

### ISSUE THREAD

**Issue by selmison** [grafana/cuetsy#63]
Couldn't [HOF](https://github.com/hofstadter-io/hof) be used to perform this conversion instead of creating the new tool from scratch?

**Comment by sdboyer** [comment]
Apologies for slow response! This issue made me realize i don't have universal notifications on for this repo.

Hof's take is philosophically different than cuetsy's. Not wrong - just different. Their [stance](https://docs.hofstadter.io/code-generation/type-and-structs/#generating-types) is that it's hard to construct an actual type relation between CUE and different languages, so templating is the preferable approach.

I agree that it's hard. But for cuetsy (and [thema](https://github.com/grafana/thema), and grafana itself, the larger context that motivated the existence of cuetsy), that's where the value is - a single source of truth for common types (like grafana dashboards) that's shared and propagated across different language contexts. Cuetsy is what gives us that - the ability to write [a schema in CUE](https://github.com/grafana/grafana/blob/654db452cd33554c718769df185d81476a914b44/pkg/coremodel/dashboard/coremodel.cue) that can be accurately, though not perfectly, represented in [TypeScript](https://github.com/grafana/grafana/blob/main/packages/grafana-schema/src/raw/dashboard/x/dashboard.gen.ts). (We get our [Go](https://github.com/grafana/grafana/blob/654db452cd33554c718769df185d81476a914b44/pkg/coremodel/dashboard/dashboard_gen.go) representation by hopping through OpenAPI, for now)
