### ISSUE TITLE
List defaults

### ISSUE THREAD

**Issue by sh0rez** [grafana/cuetsy#8]
This currently panics:

```cue
I2: {
  I2_TypedList: [...int] | *[1,2]
} @cuetsy(targetType="interface")
```

Instead, it should generate an interface with a `number[]` field and a default const with `[1,2]`

**Comment by ying-jeanne** [comment]
we need to distinguish somehow the list intent to be empty default or the case when it is just false return of cue.default()

**Comment by ying-jeanne** [comment]
the current pr works for a homogeneous list with or without defaults. 
```
    Defining array with multiple types in TypeScript

Use a union type (string|number)[] demo:

const foo: (string|number)[] = [ 1, "message" ];

    I have an array of the form: [ 1, "message" ].

If you are sure that there are always only two elements [number, string] then you can declare it as a tuple:

const foo: [number, string] = [ 1, "message" ];

```
we can also support union and tuple?(maybe not) in the following stage.
